name: Deploy

on:
  push:
    branches:
      - docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ env.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_USERNAME |
          echo $DOCKER_PASSWORD |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Docker build
        run: docker build . --file Dockerfile --tag fonmolodtsev/cloud-front:$(date +%s)
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cloud-front
